### ISSUE TITLE
RHEL 7 ('ip' tool not found) error

### ISSUE THREAD

**Issue by crayroot** [elastic/ansible-elastic-cloud-enterprise#111]
Installed fresh 7.9 RHEL DVD ISO using VBox locally. Script throws the error seen in #51 resolved by (https://github.com/elastic/ansible-elastic-cloud-enterprise/commit/a8df0d5cbef0646d0fdea15c43048257b70feeec).

IP tool is installed. I discovered that the main.yml within tasks/base/RedHat-7 do not include the same configurations that allow the server to discover the IP address:

```
- name: ensure dhcp dns is set
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: "{{ item }}"
  with_items:
    - 'PeerDNS=yes'
    - 'NM_CONTROLLED=yes'

- name: set locale
  lineinfile:
    path: /etc/environment
    line: "{{ item }}"
  with_items:
    - 'LANG=en_US.utf8'
    - 'LC_CTYPE=en_US.utf8'

- name: set path
  lineinfile:
    path: /etc/profile.d/path.sh
    line: "export PATH=$PATH:/usr/sbin"
    create: yes
```

Also, by default, VirtualBox renames eth0 to enp0s3, and it does not appear that the ansible-elastic role checks for the name of the interface. I followed this guide to rename enp0s3 to eth0, and after updating the main.yml above, the installation completes successfully:

https://www.linuxtopic.com/2017/02/how-to-change-default-interface-name.html
