### ISSUE TITLE
Provide sensible defaults for memory settings

### ISSUE THREAD

**Issue by selste** [elastic/ansible-elastic-cloud-enterprise#22]
The ECE default memory settings are pretty much useless.
We set up a test installation and used the settings as documented for a 'Small baseline installation' for the primary node, but - accidentally - the secondary and tertiary node did not.
End result was that secondary and tertiary started, but could not be administered via Cloud UI - worse, they could not be /removed/ and we had to ditch the whole installation and start all over again.
On the plus side: installation is really fast!

We're currently using a dirty hack to solve this problem.
In 'bootstrap/main.yml' the task
`-name: Memory settings for ECE
  set_fact:
    ece_memory_settings: ' {"runner:{"xms":"1G","xmx":"1G"}[...]}'
`
defines a variable and add
`--memory-settings '{{ ece_memory_settings }}'`
in the respective 'install_stack.yml' to the install script call (the whitespace before '{' is necessary, otherwise the line is not treated simply as text.

This is definitely the wrong way to do this - but it works for us so far!
A better approach might be to define variables for each (ECE) role and read the values from the 'inventory.yml' file?

**Comment by vaubarth** [comment]
You are right, we should deal with sensible values here and make them nicely configurable.
I will have a look next week.

**Comment by vaubarth** [comment]
So I would add a new variable for the role `memory` which is itself a dict that represents the different roles and is then passed to the installation:
```yaml
- hosts: primary
  roles:
    - elastic-cloud-enterprise
  vars:
    memory:
      runner:
      allocator:
      proxy:
      zookeeper:
      director:
      constructor:
      admin-console:
...
```

these will have sensible defaults but can be overriden by the user.
