### ISSUE TITLE
Persist ip_conntrack after reboot

### ISSUE THREAD

**Issue by vaubarth** [elastic/ansible-elastic-cloud-enterprise#29]
`ip_conntrack` is currently loaded via ansible `modprobe` which does not persist it anywhere.

We need to create a `/etc/modules-load.d/` file in a seperate task (e.g. `ip_conntrack.conf`)

**Comment by selste** [comment]
One of our Admins dug around a little bit and found out that dockerd forces the ip_conntrack module to be loaded (on our RHEL 7.6 systems) if necessary.
I've added a separate YAML file to the RHEL-7 folder called 'kernel_modules.yml':
```
---
- name: Enable kernel modules
  template:
   src: templates/module.conf.j2
   dest: "/etc/modules-load.d/{{ item.name }}.conf"
  with_items:
  - { name: 'conntrack', kernel_module: 'ip_conntrack' }
  - { name: 'overlay', kernel_module: 'overlay' }
```
and - of course - a simple template 'module.conf.j2' consisting of:
```
{{ item.kernel_module }}
```
It's reasonably generic, although there is a redundancy: the overlay kernel module is also defined in 'vars/os_[Distro].yml'.
