### ISSUE TITLE
uid 1001 for the elastic user might already be in use

### ISSUE THREAD

**Issue by sachinfrayne** [elastic/ansible-elastic-cloud-enterprise#37]
```
- name: Add user elastic
  user:
    name: elastic
    uid: 1001
    group: elastic
    groups: docker
    append: yes
    state: present
    generate_ssh_key: true
  when: getent_passwd["elastic"] == none
```

Should `uid` be auto-generated if the number 1001 is already in use?
