### ISSUE TITLE
Add support for ece-support-diagnostics

### ISSUE THREAD

**Issue by thomasklinger1234** [elastic/ansible-elastic-cloud-enterprise#38]
## Description 

It would be pretty useful to have ece-support-diagnostics (https://github.com/elastic/ece-support-diagnostics) available in the default installation as well.

## Solution

Include the support diagnostics script at preparation time in the same way as the ECE installation/management script.

```yaml

- name: Download ece support diagnostics
  get_url:
    url: "{{ ece_supportdiagnostics_url }}"
    dest: /home/elastic/ece-support-diagnostics.sh
    mode: 0755
```
