### ISSUE TITLE
Ansible install when a proxy is being used

### ISSUE THREAD

**Issue by sachinfrayne** [elastic/ansible-elastic-cloud-enterprise#40]
When installing ECE inside a more sandboxed environment we needed to add in some proxy settings.

I took a copy of the settings that were added, but I did not test this to know exactly which settings were definitely needed and which are duplicates etc.

```
---
- hosts: all
  vars:
    http_proxy: http://<proxy_ip>:8080
    https_proxy: https://<proxy_ip>:8080
    proxy_host: <proxy_ip>
    proxy_port: 8080
    proxy_env:
      http_proxy: "{{ http_proxy }}"
      https_proxy: "{{ https_proxy }}"
    no_proxy: <primary_hostname>
```

When I get a chance I will test them, but putting this here as a placeholder and in case someone already knows the answer.
