### ISSUE TITLE
Always assumes that network interface is called eth0

### ISSUE THREAD

**Issue by xucito** [elastic/ansible-elastic-cloud-enterprise#60]
The playbook always assumes that the network interface is eth0.

in `main.yml`
```
- name: ensure dhcp dns is set
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: "{{ item }}"
  with_items:
    - 'PeerDNS=yes'
    - 'NM_CONTROLLED=yes'
```

My suggestion is to allow this to be passed via variable.
