### ISSUE TITLE
Error /etc/cloud/cloud.cfg.d/ no file or directory

### ISSUE THREAD

**Issue by sachin-frayne** [elastic/ansible-elastic-cloud-enterprise#62]
Error `/etc/cloud/cloud.cfg.d/` no file or directory

Files affected:

`tasks/base/general/make_user.yml`
`tasks/base/main.yml`

Potential solution, add task to ensure `/etc/cloud/cloud.cfg.d/` directory is present, not certain on which file to add it too though, most like guess `tasks/base/main.yml`.

```
- name: ansible create directory
  file:
    path: /etc/cloud/cloud.cfg.d/
    state: directory
```

My shorter temporary workaround change `/etc/cloud/cloud.cfg.d/` to `/tmp/` is both the files mentioned above.
